import {
  DATA_PREFIX
} from '../utils/constants'

export const CHANGE_CURRENT_SONG = `${DATA_PREFIX}/CHANGE_CURRENT_SONG`

export const CHANGE_CURRENT_SONG_INDEX = `${DATA_PREFIX}/CHANGE_CURRENT_SONG_INDEX`
export const CHANGE_PLAY_LIST = `${DATA_PREFIX}/CHANGE_PLAY_LIST`
export const CHANGE_PLAY_SEQUENCE = `${DATA_PREFIX}/CHANGE_PLAY_SEQUENCE`

export const CHANGE_CURRENT_LYRIC = `${DATA_PREFIX}/CHANGE_CURRENT_LYRIC`
export const CHANGE_CURRENT_LYRIC_INDEX = `${DATA_PREFIX}/CHANGE_CURRENT_LYRIC_INDEX`

export const CHANGE_PLAYER_PANEL = `${DATA_PREFIX}/CHANGE_PLAYER_PANEL`

export const CHANGE_SIMI_PLAYLIST = `${DATA_PREFIX}/CHANGE_SIMI_PLAYLIST`
export const CHANGE_SIMI_SONGS = `${DATA_PREFIX}/CHANGE_SIMI_SONGS`