import {
  DATA_PREFIX
} from '../utils/constants'

export const CHANGE_CURRENT_SONG = `${DATA_PREFIX}/CHANGE_CURRENT_SONG`

export const CHANGE_CURRENT_SONG_INDEX = `${DATA_PREFIX}/CHANGE_CURRENT_SONG_INDEX`
export const CHANGE_PLAY_LIST = `${DATA_PREFIX}/CHANGE_PLAY_LIST`
export const CHANGE_PLAY_SEQUENCE = `${DATA_PREFIX}/CHANGE_PLAY_SEQUENCE`